name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    
    steps:
    - name: Auto-assign PR to author
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees: [context.payload.pull_request.user.login]
          });
    
    - name: Add labels based on files changed
      uses: actions/github-script@v7
      with:
        script: |
          const { data: files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          const labels = [];
          
          const hasJsChanges = files.some(file => file.filename.endsWith('.js'));
          const hasCssChanges = files.some(file => file.filename.endsWith('.css'));
          const hasManifestChanges = files.some(file => file.filename === 'manifest.json');
          const hasDocsChanges = files.some(file => file.filename.endsWith('.md'));
          
          if (hasJsChanges) labels.push('javascript');
          if (hasCssChanges) labels.push('css');
          if (hasManifestChanges) labels.push('manifest');
          if (hasDocsChanges) labels.push('documentation');
          
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
          }